// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthPassword struct {
	ID                pgtype.UUID
	EncryptedPassword string
}

type AuthUser struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID       pgtype.UUID
	Name     string
	IsActive pgtype.Bool
}
